import { zodResolver } from '@hookform/resolvers/zod';
import { Camera, Rocket, Save, Send } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { paymentSoonMessage, toast } from '../lib/toast';
import { go } from '../lib/utils';
import { categories } from '../data/categories';
import { createListing, createOffer, getCurrentProfile, updateProviderProfile } from '../services/marketplace';
import { Button, Card } from './ui';
const input='mt-1 w-full rounded-lg border border-zs-primary/15 bg-white px-3 py-2 outline-none focus:ring-2 focus:ring-zs-accent';
const listingSchema=z.object({title:z.string().min(10,'Başlık en az 10 karakter olmalı.').max(100,'Başlık en fazla 100 karakter olmalı.'),description:z.string().min(30,'Açıklama en az 30 karakter olmalı.').max(1200,'Açıklama en fazla 1200 karakter olmalı.'),category_id:z.string().min(1,'Kategori seçmelisin.'),budget_min:z.coerce.number().min(0,'Minimum bütçe 0 veya üzeri olmalı.'),budget_max:z.coerce.number().min(0),city:z.string().optional(),is_remote:z.boolean().default(true),is_urgent:z.boolean().default(false),images:z.any().optional()}).refine(v=>v.budget_max>=v.budget_min,{path:['budget_max'],message:'Maksimum bütçe minimumdan düşük olamaz.'}).refine(v=>v.is_remote || Boolean(v.city),{path:['city'],message:'Şehir veya Online seçimi gerekli.'});
export function ListingForm(){ const {register,handleSubmit,formState:{errors}}=useForm({resolver:zodResolver(listingSchema),defaultValues:{is_remote:true,is_urgent:false,budget_min:500,budget_max:2000}}); return <Card className="mx-auto max-w-3xl p-6"><h1 className="font-serif text-4xl font-bold text-zs-primary">Talep Oluştur</h1><p className="mt-2 text-zs-muted">Talebini bırak, en hızlısı sana gelsin.</p><form className="mt-6 grid gap-4" onSubmit={handleSubmit((data:any)=>{ const files=data.images as FileList|undefined; if(files && files.length>3){ toast('En fazla 3 görsel yükleyebilirsin.'); return; } const l=createListing({...data, city:data.is_remote?'Online':data.city, images:[]}); toast('Talebin başarıyla oluşturuldu.'); go('/ilanlar/'+l.id); })}><label>Başlık<input className={input} {...register('title')}/><Err e={errors.title?.message}/></label><label>Açıklama<textarea className={input} rows={6} {...register('description')}/><Err e={errors.description?.message}/></label><label>Kategori<select className={input} {...register('category_id')}><option value="">Seç</option><optgroup label="Akıllı İşler">{categories.filter(c=>c.group==='smart').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</optgroup><optgroup label="Klasik Hizmetler">{categories.filter(c=>c.group==='classic').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</optgroup></select><Err e={errors.category_id?.message}/></label><div className="grid gap-3 md:grid-cols-2"><label>Bütçe min<input type="number" className={input} {...register('budget_min')}/><Err e={errors.budget_min?.message}/></label><label>Bütçe max<input type="number" className={input} {...register('budget_max')}/><Err e={errors.budget_max?.message}/></label></div><div className="grid gap-3 md:grid-cols-2"><label>Şehir<input className={input} {...register('city')}/><Err e={errors.city?.message}/></label><label className="flex items-center gap-2 pt-7"><input type="checkbox" {...register('is_remote')}/> Online yapılabilir</label></div><label className="flex items-center gap-2"><input type="checkbox" {...register('is_urgent')}/> Acil mi?</label><label className="rounded-lg border border-dashed border-zs-primary/20 p-4"><span className="flex items-center gap-2 font-semibold"><Camera size={18}/> Maksimum 3 görsel</span><input type="file" multiple accept="image/*" className="mt-2" {...register('images')}/></label><Button><Rocket size={18}/> Talebi Yayınla</Button></form></Card> }
function Err({e}:{e:any}){ return e?<p className="mt-1 text-sm text-zs-urgent">{String(e)}</p>:null }
export function OfferForm({listingId}:{listingId:string}){ const schema=z.object({price:z.coerce.number().min(1,'Fiyat girmelisin.'),duration_text:z.string().min(2,'Süre yazmalısın.'),message:z.string().min(20,'Mesaj en az 20 karakter olmalı.')}); const {register,handleSubmit,formState:{errors},reset}=useForm({resolver:zodResolver(schema)}); return <Card className="p-5"><h2 className="font-serif text-2xl font-bold text-zs-primary">Teklif Ver</h2><p className="mt-1 text-sm text-zs-muted">Güvenlik için iletişim bilgileri teklif kabul edilene kadar gizlenir.</p><form className="mt-4 grid gap-3" onSubmit={handleSubmit((data:any)=>{ try{ createOffer({listing_id:listingId,...data}); toast('Teklifin gönderildi.'); reset(); window.dispatchEvent(new PopStateEvent('popstate')); }catch(e:any){ toast(e.message); } })}><label>Fiyat<input type="number" className={input} {...register('price')}/><Err e={errors.price?.message}/></label><label>Süre metni<input className={input} placeholder="Örn. 2 gün" {...register('duration_text')}/><Err e={errors.duration_text?.message}/></label><label>Mesaj<textarea className={input} rows={4} {...register('message')}/><Err e={errors.message?.message}/></label><Button><Send size={18}/> Teklif Gönder</Button></form></Card> }
export function ProfileEditForm(){ const p=getCurrentProfile(); const {register,handleSubmit,watch,formState:{errors}}=useForm({defaultValues:{...p,skills:p.skills.join(', ')}}); const isProvider=watch('is_provider'); return <Card className="mx-auto max-w-3xl p-6"><h1 className="font-serif text-4xl font-bold text-zs-primary">Profilim</h1><form className="mt-6 grid gap-4" onSubmit={handleSubmit((d:any)=>{ if(d.is_provider && !d.provider_title){ toast('Çözüm Veren başlığı zorunlu.'); return; } updateProviderProfile({...d,id:p.id,skills:String(d.skills||'').split(',').map((s:string)=>s.trim()).filter(Boolean),price_from:d.price_from?Number(d.price_from):null}); toast(d.is_provider?'Çözüm Veren profilin artık görünür.':'Profilin güncellendi.'); })}><label>Ad Soyad<input className={input} {...register('full_name')}/></label><label>Şehir<input className={input} {...register('city')}/></label><label>Biyografi<textarea className={input} rows={3} {...register('bio')}/></label><label className="flex items-center gap-2 rounded-lg bg-zs-bg p-4"><input type="checkbox" {...register('is_provider')}/> Çözüm Veren olarak görünmek istiyorum</label>{isProvider&&<div className="grid gap-4 rounded-xl border border-zs-accent/30 bg-zs-accent/5 p-4"><label>Çözüm Veren başlığı<input className={input} {...register('provider_title',{required:true})}/>{errors.provider_title&&<Err e="provider_title zorunlu"/>}</label><label>Tanıtım (max 280)<textarea maxLength={280} className={input} rows={3} {...register('provider_intro')}/></label><label>Başlangıç fiyatı<input type="number" className={input} {...register('price_from')}/></label><label>Yetenekler (virgülle ayır)<input className={input} {...register('skills')}/></label></div>}<Button><Save size={18}/> Kaydet</Button></form></Card> }
export function PromotionPlaceholderButton({children}:{children:React.ReactNode}){ return <Button variant="secondary" onClick={()=>toast(paymentSoonMessage)}>{children}</Button> }
