import { CheckCircle2, MapPin } from 'lucide-react';
import { toast } from '../lib/toast';
import { money } from '../lib/utils';
import { acceptOffer, currentUserId, getOffersForListing } from '../services/marketplace';
import type { ListingWithCategory } from '../types';
import { CountdownBadge, PromotionBadge, UrgencyBadge } from './badges';
import { OfferForm, PromotionPlaceholderButton } from './Forms';
import { Badge, Button, Card } from './ui';
export function ListingDetail({listing}:{listing:ListingWithCategory}){ const offers=getOffersForListing(listing.id); const mine=listing.owner_id===currentUserId(); const active=listing.status==='active'; return <div className="mx-auto grid max-w-7xl gap-6 px-4 py-8 lg:grid-cols-[1fr_380px]"><article><Card className="p-6"><div className="flex flex-wrap gap-2"><Badge className="bg-zs-primary/10 text-zs-primary">{listing.category.name}</Badge><CountdownBadge expiresAt={listing.expires_at}/>{listing.is_urgent&&<UrgencyBadge/>}{listing.is_promoted&&<PromotionBadge/>}{!active&&<Badge className="bg-zs-urgent text-white">Bu talebin süresi dolmuş.</Badge>}</div><h1 className="mt-5 font-serif text-4xl font-bold text-zs-primary">{listing.title}</h1><p className="mt-4 whitespace-pre-line text-lg text-zs-text">{listing.description}</p><div className="mt-6 flex flex-wrap gap-3"><Badge className="bg-zs-accent/15 text-zs-accent">{money(listing.budget_min)} - {money(listing.budget_max)}</Badge><Badge className="bg-white text-zs-muted"><MapPin size={14}/>{listing.is_remote?'Online':listing.city}</Badge></div><div className="mt-6 flex flex-wrap gap-3"><PromotionPlaceholderButton>Öne Çıkar</PromotionPlaceholderButton><PromotionPlaceholderButton>Acele Rozeti Al</PromotionPlaceholderButton><PromotionPlaceholderButton>Yenile</PromotionPlaceholderButton></div></Card><OfferList listingOwner={mine} offers={offers}/></article><aside>{active && !mine ? <OfferForm listingId={listing.id}/> : <Card className="p-5 text-zs-muted">{mine?'Bu talebin sahibi sensin. Gelen teklifleri aşağıdan yönetebilirsin.':'Bu talebe teklif verilemez.'}</Card>}</aside></div> }
export function OfferList({offers, listingOwner}:{offers:any[]; listingOwner:boolean}){ return <Card className="mt-6 p-6"><h2 className="font-serif text-2xl font-bold text-zs-primary">Teklifler</h2>{offers.length===0?<p className="mt-3 text-zs-muted">Henüz teklif yok.</p>:<div className="mt-4 grid gap-3">{offers.map(o=><div className="rounded-xl bg-zs-bg p-4" key={o.id}><div className="flex flex-wrap items-center justify-between gap-2"><b>{o.sender.full_name}</b><Badge className="bg-white text-zs-primary">{money(o.price)} · {o.duration_text} · {statusText(o.status)}</Badge></div><p className="mt-2 text-sm text-zs-muted">{o.sanitized_message}</p>{listingOwner&&o.status==='pending'&&<Button className="mt-3" onClick={()=>{acceptOffer(o.id); toast('Teklif kabul edildi.'); window.dispatchEvent(new PopStateEvent('popstate'));}}><CheckCircle2 size={18}/> Teklifi Kabul Et</Button>}</div>)}</div>}</Card> }
const statusText=(s:string)=>s==='accepted'?'Kabul edildi':s==='rejected'?'Reddedildi':s==='withdrawn'?'Geri çekildi':'Bekliyor';
