import * as Icons from 'lucide-react';
import type { ListingWithCategory } from '../types';
import { go, money } from '../lib/utils';
import { CountdownBadge, PromotionBadge, UrgencyBadge } from './badges';
import { Badge, Button, Card, EmptyState } from './ui';
import { getActiveListingCount, getHotListings, getWeeklyListings } from '../services/marketplace';
export function HotListingCard({listing}:{listing:ListingWithCategory}){ const Icon=(Icons as any)[listing.category.icon] ?? Icons.Sparkles; return <Card onClick={()=>go('/ilanlar/'+listing.id)} className="group cursor-pointer p-5 transition hover:-translate-y-1 hover:shadow-soft"><div className="flex items-start justify-between gap-3"><Badge className="bg-zs-primary/10 text-zs-primary"><Icon size={14}/>{listing.category.name}</Badge><CountdownBadge expiresAt={listing.expires_at}/></div><h3 className="mt-4 line-clamp-2 min-h-[3.2rem] font-serif text-xl font-bold text-zs-primary">{listing.title}</h3><p className="mt-2 line-clamp-2 text-sm text-zs-muted">{listing.description}</p><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-lg font-extrabold text-zs-accent">{money(listing.budget_min)} - {money(listing.budget_max)}</span><Badge className="bg-white text-zs-muted">{listing.is_remote?'Online':listing.city}</Badge>{listing.is_urgent&&<UrgencyBadge/>}{listing.is_promoted&&<PromotionBadge/>}</div></Card> }
export function HotListingsSection(){ const listings=getHotListings(); return <section className="mx-auto max-w-7xl px-4 py-8"><div className="mb-5"><h2 className="font-serif text-4xl font-bold text-zs-primary">Sıcak Talepler</h2><p className="text-zs-muted">Şu an açık talepler. Hızlı ol, süre azalıyor.</p></div>{listings.length===0?<EmptyState title="Henüz sıcak talep yok — ilk talebi sen aç." action={<Button onClick={()=>go('/talep-olustur')}>Talep Oluştur</Button>}/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{listings.map(l=><HotListingCard key={l.id} listing={l}/>)}</div>}<div className="mt-6 text-center"><Button variant="secondary" onClick={()=>go('/ilanlar')}>Tüm Talepleri Gör · {getActiveListingCount()} aktif</Button></div></section> }
export function WeeklyListings(){ const listings=getWeeklyListings(); return <section className="mx-auto max-w-7xl px-4 py-8"><h2 className="font-serif text-3xl font-bold text-zs-primary">Bu Hafta Açılanlar</h2><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{listings.map(l=><button onClick={()=>go('/ilanlar/'+l.id)} className="rounded-xl bg-white p-4 text-left text-sm shadow-sm" key={l.id}><b>{l.title}</b><p className="mt-1 text-zs-accent">{money(l.budget_min)} - {money(l.budget_max)}</p></button>)}</div></section> }
