import { useEffect, useMemo, useState } from 'react';
import { ClassicCategoriesSection, SmartCategoriesSection } from './components/Categories';
import { ListingForm, ProfileEditForm, PromotionPlaceholderButton } from './components/Forms';
import { HeroSection } from './components/HeroSection';
import { HotListingCard, HotListingsSection, WeeklyListings } from './components/ListingCards';
import { ListingDetail } from './components/ListingDetail';
import { AppLayout } from './components/AppLayout';
import { ProviderCard, ProviderSidebar } from './components/Providers';
import { Badge, Button, Card, EmptyState, LoadingSkeleton, Toast } from './components/ui';
import { basePath, go } from './lib/utils';
import { useAsyncValue } from './lib/useAsyncValue';
import type { ListingWithCategory, Offer, Profile } from './types';
import { getAllListings, getAllProviderProfiles, getListingById, getMyListings, getMyNotifications, getMyOffers, getProfile, getReviewsForProfile, markNotificationRead, resetDemoData, signIn, signOut, signUp } from './services/marketplace';
import { toast } from './lib/toast';

function currentAppPath() { const base = basePath(); const pathname = base && location.pathname.startsWith(base) ? location.pathname.slice(base.length) || '/' : location.pathname; return pathname + location.search; }
function usePath() { const [path, setPath] = useState(currentAppPath()); useEffect(() => { const f = () => setPath(currentAppPath()); addEventListener('popstate', f); return () => removeEventListener('popstate', f); }, []); return path; }
export default function App() { const path = usePath(); return <AppLayout><Toast /><Router path={path} /></AppLayout>; }
function Home() { return <><HeroSection /><div className="mx-auto grid max-w-7xl gap-6 px-4 lg:grid-cols-[1fr_360px]"><div><HotListingsSection /></div><ProviderSidebar /></div><SmartCategoriesSection /><ClassicCategoriesSection /><WeeklyListings /><Ad /></>; }

function Listings() {
  const params = new URLSearchParams(location.search); const group = params.get('grup') as any; const q = params.get('q') || '';
  const loader = useMemo(() => () => getAllListings({ group: group === 'smart' || group === 'classic' ? group : undefined, q }), [group, q]);
  const { value: listings, loading } = useAsyncValue(loader, [loader], [] as ListingWithCategory[]);
  return <section className="mx-auto max-w-7xl px-4 py-8"><h1 className="font-serif text-4xl font-bold text-zs-primary">Sıcak Talepler</h1><p className="text-zs-muted">Akıllı ve klasik talepleri filtrele.</p><div className="mt-4 flex flex-wrap gap-2"><Button variant={!group ? 'primary' : 'secondary'} onClick={() => go('/ilanlar')}>Tümü</Button><Button variant={group === 'smart' ? 'primary' : 'secondary'} onClick={() => go('/ilanlar?grup=smart')}>Akıllı İşler</Button><Button variant={group === 'classic' ? 'primary' : 'secondary'} onClick={() => go('/ilanlar?grup=classic')}>Klasik Hizmetler</Button></div><Ad />{loading ? <LoadingSkeleton /> : <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{listings.map((l) => <HotListingCard key={l.id} listing={l} />)}</div>}{!loading && listings.length === 0 && <EmptyState title="Aradığın kriterlere uygun talep bulunamadı." action={<Button onClick={() => go('/talep-olustur')}>Talep Oluştur</Button>} />}</section>;
}

function Router({ path }: { path: string }) { const clean = path.split('?')[0]; if (clean === '/') return <Home />; if (clean === '/ilanlar') return <Listings />; if (clean.startsWith('/ilanlar/')) return <ListingRoute id={clean.split('/')[2]} />; if (clean === '/talep-olustur') return <div className="px-4 py-8"><ListingForm /></div>; if (clean === '/profilim') return <div className="px-4 py-8"><ProfileEditForm /></div>; if (clean === '/cozum-verenler') return <ProvidersPage />; if (clean === '/bildirimler') return <NotificationsPage />; if (clean.startsWith('/u/') || clean.startsWith('/profil/')) return <PublicProfile id={clean.split('/').pop()!} />; if (clean === '/taleplerim') return <MyListings />; if (clean === '/tekliflerim') return <MyOffers />; if (clean === '/giris' || clean === '/kayit') return <AuthPage type={clean === '/giris' ? 'login' : 'register'} />; if (['/hakkimizda', '/sss', '/kvkk', '/iletisim'].includes(clean)) return <StaticPage title={clean.slice(1).toLocaleUpperCase('tr')} />; return <NotFound />; }
function ListingRoute({ id }: { id: string }) { const { value, loading } = useAsyncValue(() => getListingById(id), [id], null as ListingWithCategory | null); if (loading) return <div className="mx-auto max-w-4xl px-4 py-8"><LoadingSkeleton /></div>; return value ? <ListingDetail listing={value} /> : <NotFound />; }
function ProvidersPage() { const { value: providers, loading } = useAsyncValue(getAllProviderProfiles, [], [] as Profile[]); return <section className="mx-auto max-w-7xl px-4 py-8"><h1 className="font-serif text-4xl font-bold text-zs-primary">Çözüm Verenler</h1>{loading ? <LoadingSkeleton /> : <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{providers.map((p) => <ProviderCard key={p.id} profile={p} />)}</div>}</section>; }
function PublicProfile({ id }: { id: string }) { const { value: p, loading } = useAsyncValue(() => getProfile(id), [id], null as Profile | null); const { value: reviews } = useAsyncValue(() => getReviewsForProfile(id), [id], [] as any[]); if (loading) return <div className="mx-auto max-w-4xl px-4 py-8"><LoadingSkeleton /></div>; if (!p) return <NotFound />; return <section className="mx-auto max-w-4xl px-4 py-8"><Card className="p-8"><h1 className="font-serif text-4xl font-bold text-zs-primary">{p.full_name}</h1><p className="mt-2 text-xl text-zs-muted">{p.provider_title || 'ZamanSepeti üyesi'}</p><p className="mt-4">{p.provider_intro || p.bio}</p><div className="mt-4 flex flex-wrap gap-2">{p.skills.map((s) => <Badge className="bg-zs-primary/10 text-zs-primary" key={s}>{s}</Badge>)}<Badge className="bg-zs-accent/15 text-zs-accent">{p.rating ? `${p.rating} puan` : 'Yeni üye'}</Badge><Badge className="bg-white text-zs-muted">{p.city || 'Online'}</Badge></div><Button className="mt-6" onClick={() => toast('Davet özelliği yakında')}>Bu Kişiyi Talebe Davet Et</Button></Card><Card className="mt-6 p-6"><h2 className="font-serif text-2xl font-bold text-zs-primary">Değerlendirmeler</h2>{reviews.length === 0 ? <p className="mt-2 text-zs-muted">Henüz değerlendirme yok.</p> : reviews.map((r: any) => <p key={r.id} className="mt-3 rounded-lg bg-zs-bg p-3">{r.rating}/5 · {r.comment}</p>)}</Card></section>; }

function AuthPage({ type }: { type: 'login' | 'register' }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [fullName, setFullName] = useState(''); const [busy, setBusy] = useState(false);
  return <section className="mx-auto max-w-md px-4 py-12"><Card className="p-6"><h1 className="font-serif text-3xl font-bold text-zs-primary">{type === 'login' ? 'Giriş' : 'Kayıt Ol'}</h1><p className="mt-2 text-zs-muted">Supabase Auth ile güvenli giriş yap.</p><form className="mt-5 grid gap-3" onSubmit={async (e) => { e.preventDefault(); setBusy(true); try { if (type === 'login') await signIn(email, password); else await signUp(email, password, fullName || email.split('@')[0]); toast(type === 'login' ? 'Giriş yapıldı.' : 'Kayıt oluşturuldu. E-posta doğrulaması istenirse gelen kutunu kontrol et.'); go('/profilim'); } catch (err: any) { toast(err.message || 'İşlem başarısız.'); } finally { setBusy(false); } }}>{type === 'register' && <label>Ad Soyad<input className="mt-1 w-full rounded-lg border border-zs-primary/15 px-3 py-2" value={fullName} onChange={(e) => setFullName(e.target.value)} /></label>}<label>E-posta<input type="email" required className="mt-1 w-full rounded-lg border border-zs-primary/15 px-3 py-2" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Şifre<input type="password" required minLength={6} className="mt-1 w-full rounded-lg border border-zs-primary/15 px-3 py-2" value={password} onChange={(e) => setPassword(e.target.value)} /></label><Button disabled={busy}>{busy ? 'İşleniyor' : type === 'login' ? 'Giriş Yap' : 'Kayıt Ol'}</Button></form><Button variant="ghost" className="mt-3" onClick={async () => { await signOut(); toast('Çıkış yapıldı.'); }}>Çıkış Yap</Button><p className="mt-4 text-sm">{type === 'login' ? 'Hesabın yok mu?' : 'Zaten hesabın var mı?'} <button className="font-bold text-zs-accent" onClick={() => go(type === 'login' ? '/kayit' : '/giris')}>{type === 'login' ? 'Kayıt ol' : 'Giriş yap'}</button></p></Card></section>;
}
function MyListings() { const { value: listings, loading } = useAsyncValue(getMyListings, [], [] as ListingWithCategory[]); return <section className="mx-auto max-w-7xl px-4 py-8"><h1 className="font-serif text-4xl font-bold text-zs-primary">Taleplerim</h1>{loading ? <LoadingSkeleton /> : <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{listings.map((l) => <HotListingCard key={l.id} listing={l} />)}</div>}</section>; }
function MyOffers() { const { value: offers, loading } = useAsyncValue(getMyOffers, [], [] as Offer[]); return <section className="mx-auto max-w-4xl px-4 py-8"><h1 className="font-serif text-4xl font-bold text-zs-primary">Tekliflerim</h1>{loading ? <LoadingSkeleton /> : <div className="mt-6 grid gap-3">{offers.map((o) => <Card key={o.id} className="p-4"><b>{o.price} ₺ · {o.duration_text}</b><p className="text-sm text-zs-muted">{o.status === 'accepted' ? o.message : o.sanitized_message}</p><Badge className="mt-2 bg-zs-primary/10 text-zs-primary">{o.status}</Badge></Card>)}</div>}</section>; }
function NotificationsPage() { const { value: items, loading, reload } = useAsyncValue(getMyNotifications, [], []); return <section className="mx-auto max-w-4xl px-4 py-8"><h1 className="font-serif text-4xl font-bold text-zs-primary">Bildirimler</h1>{loading ? <LoadingSkeleton /> : <div className="mt-6 grid gap-3">{items.length === 0 && <EmptyState title="Henüz bildirimin yok." />}{items.map((n) => <Card key={n.id} className="p-4"><div className="flex items-center justify-between gap-3"><div><b>{n.title}</b><p className="text-sm text-zs-muted">{n.body}</p></div>{!n.read_at && <Button variant="secondary" onClick={async () => { await markNotificationRead(n.id); reload(); }}>Okundu</Button>}</div></Card>)}</div>}</section>; }
function StaticPage({ title }: { title: string }) { return <section className="mx-auto max-w-4xl px-4 py-10"><Card className="p-8"><h1 className="font-serif text-4xl font-bold text-zs-primary">{title}</h1><p className="mt-4 text-zs-muted">ZamanSepeti, zamanı olmayan ama bütçesi olan kişilerin talep açtığı; çözüm verenlerin bu taleplere teklif verdiği talep odaklı marketplace MVP’sidir.</p><PromotionPlaceholderButton>Ödeme özelliklerini incele</PromotionPlaceholderButton></Card></section>; }
function Ad() { return <div className="mx-auto my-8 max-w-7xl rounded-xl border border-dashed border-zs-primary/25 bg-white/60 p-8 text-center text-zs-muted"><b>REKLAM ALANI</b><br />Burada sponsorlu içerik gösterilecek.</div>; }
function NotFound() { return <section className="mx-auto max-w-3xl px-4 py-16"><EmptyState title="Sayfa bulunamadı." action={<Button onClick={() => go('/')}>Ana sayfa</Button>} /><div className="mt-4 text-center"><Button variant="secondary" onClick={() => { resetDemoData(); toast('Demo veri sıfırlandı.'); }}>Demo veriyi sıfırla</Button></div></section>; }
